'use client'

import { useState, useCallback } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { X, ChevronLeft, ChevronRight, ShieldCheck, Leaf } from 'lucide-react'
import { cn } from '@/lib/utils'
import { markTutorialComplete, TUTORIAL_SLIDE_COUNT } from '@/lib/tutorial'
import { useTranslations } from 'next-intl'

interface TutorialOverlayProps {
  onDismiss: () => void
}

// ── Slide visuals ──────────────────────────────────────────────────────────────

function WelcomeVisual() {
  return (
    <div
      className="w-full h-44 rounded-2xl overflow-hidden relative flex items-center justify-center"
      style={{ background: 'linear-gradient(135deg, #f59e0b 0%, #ef4444 55%, #ec4899 100%)' }}
    >
      <div
        className="absolute inset-0 opacity-25"
        style={{
          backgroundImage:
            'radial-gradient(circle at 15% 85%, white 0%, transparent 45%), radial-gradient(circle at 85% 15%, white 0%, transparent 45%)',
        }}
      />
      <div className="relative flex flex-col items-center gap-3">
        <div className="w-16 h-16 rounded-full bg-white/20 backdrop-blur-sm flex items-center justify-center">
          <Leaf className="w-8 h-8 text-white" />
        </div>
        <span className="text-white font-bold text-3xl tracking-tight">Fable</span>
      </div>
    </div>
  )
}

function AllergenVisual() {
  const allergens = [
    { icon: '🥜', name: 'Peanuts', active: true },
    { icon: '🌾', name: 'Gluten', active: true },
    { icon: '🥛', name: 'Milk', active: false },
    { icon: '🥚', name: 'Eggs', active: false },
    { icon: '🐟', name: 'Fish', active: false },
    { icon: '🦐', name: 'Shellfish', active: false },
    { icon: '🫘', name: 'Soy', active: false },
    { icon: '🌰', name: 'Tree Nuts', active: true },
    { icon: '🌿', name: 'Celery', active: false },
    { icon: '🌱', name: 'Mustard', active: false },
    { icon: '🐚', name: 'Molluscs', active: false },
    { icon: '⚗️', name: 'Sulphites', active: false },
  ]
  return (
    <div className="grid grid-cols-6 gap-1.5 px-1">
      {allergens.map((a, i) => (
        <div
          key={i}
          className={cn(
            'aspect-square flex flex-col items-center justify-center gap-0.5 rounded-xl border-2 text-center',
            a.active ? 'border-primary bg-primary/10' : 'border-border bg-card',
          )}
        >
          <span className="text-xl leading-none">{a.icon}</span>
          <span className="text-[8px] font-medium leading-tight text-foreground px-0.5">{a.name}</span>
        </div>
      ))}
    </div>
  )
}

function KitchenVisual() {
  const tKitchen = useTranslations('kitchen')
  const sections = [
    { icon: '❄️', labelKey: 'fridge' as const, items: ['Chicken', 'Spinach', 'Yogurt'] },
    { icon: '🫙', labelKey: 'cupboard' as const, items: ['Pasta', 'Rice', 'Olive Oil'] },
  ]
  return (
    <div className="grid grid-cols-2 gap-2 px-1">
      {sections.map(section => (
        <div key={section.labelKey} className="bg-card border border-border rounded-2xl p-3">
          <div className="flex items-center gap-1.5 mb-2.5">
            <span className="text-base leading-none">{section.icon}</span>
            <span className="text-xs font-semibold text-foreground">{tKitchen(`areas.${section.labelKey}` as Parameters<typeof tKitchen>[0])}</span>
          </div>
          <div className="space-y-1.5">
            {section.items.map((item, i) => (
              <div key={item} className={cn('flex items-center gap-1.5', i < section.items.length - 1 && 'pb-1.5 border-b border-border')}>
                <div className="w-1.5 h-1.5 rounded-full bg-primary shrink-0" />
                <span className="text-xs text-muted-foreground">{item}</span>
              </div>
            ))}
          </div>
        </div>
      ))}
    </div>
  )
}

function RecipeVisual() {
  const tRecipe = useTranslations('recipe')
  const tTutorial = useTranslations('tutorial')
  return (
    <div className="px-1">
      <div className="rounded-2xl overflow-hidden border border-border bg-card shadow-sm">
        <div
          className="h-28 flex items-center justify-center relative"
          style={{ background: 'linear-gradient(135deg, #8b5cf6 0%, #3b82f6 55%, #06b6d4 100%)' }}
        >
          <span className="text-5xl">🍝</span>
          <div className="absolute bottom-2 left-3">
            <span className="text-white text-[10px] font-medium bg-white/20 backdrop-blur-sm px-2 py-0.5 rounded-full">
              Generated by Claude
            </span>
          </div>
        </div>
        <div className="px-4 py-3">
          <h4 className="text-sm font-semibold text-foreground mb-1">Garlic Butter Pasta</h4>
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <span>30 min</span>
            <span>·</span>
            <span>{tRecipe('cardServings', { count: 2 })}</span>
            <span>·</span>
            <span className="text-primary font-medium">{tTutorial('safeForYou')}</span>
          </div>
        </div>
      </div>
    </div>
  )
}

function SafeFoodsVisual() {
  const tTutorial = useTranslations('tutorial')
  const foods = ['Rice', 'Chicken Breast', 'Olive Oil', 'Carrots', 'Courgette']
  return (
    <div className="px-1">
      <div className="bg-card border border-border rounded-2xl overflow-hidden shadow-sm">
        <div className="flex items-center gap-2 px-4 py-3 border-b border-border" style={{ backgroundColor: 'rgba(34,197,94,0.06)' }}>
          <ShieldCheck className="w-4 h-4" style={{ color: '#16a34a' }} />
          <span className="text-xs font-semibold text-foreground">{tTutorial('safeFoodsList')}</span>
          <span className="ml-auto text-xs font-semibold" style={{ color: '#16a34a' }}>{tTutorial('active')}</span>
        </div>
        {foods.map((food, i) => (
          <div key={food} className={cn('flex items-center gap-3 px-4 py-2.5', i < foods.length - 1 && 'border-b border-border')}>
            <div className="w-4 h-4 rounded-full flex items-center justify-center shrink-0" style={{ backgroundColor: 'rgba(34,197,94,0.15)' }}>
              <span className="text-[9px] font-bold" style={{ color: '#16a34a' }}>✓</span>
            </div>
            <span className="text-xs text-foreground">{food}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

// ── Slides data ─────────────────────────────────────────────────────────────────

const SLIDE_IDS = ['welcome', 'allergens', 'kitchen', 'recipe', 'safe-foods'] as const
const SLIDE_VISUALS = [WelcomeVisual, AllergenVisual, KitchenVisual, RecipeVisual, SafeFoodsVisual]

// ── Animation variants ──────────────────────────────────────────────────────────

const slideVariants = {
  enter: (direction: number) => ({
    x: direction > 0 ? '100%' : '-100%',
    opacity: 0,
  }),
  center: {
    x: 0,
    opacity: 1,
    transition: { duration: 0.3, ease: [0.25, 0.46, 0.45, 0.94] as const },
  },
  exit: (direction: number) => ({
    x: direction < 0 ? '100%' : '-100%',
    opacity: 0,
    transition: { duration: 0.25, ease: [0.25, 0.46, 0.45, 0.94] as const },
  }),
}

// ── Component ───────────────────────────────────────────────────────────────────

export function TutorialOverlay({ onDismiss }: TutorialOverlayProps) {
  const [currentSlide, setCurrentSlide] = useState(0)
  const [direction, setDirection] = useState(1)
  const t = useTranslations('tutorial')

  const isLastSlide = currentSlide === TUTORIAL_SLIDE_COUNT - 1

  const slides = SLIDE_IDS.map((id, i) => {
    const Visual = SLIDE_VISUALS[i]
    return {
      id,
      visual: <Visual />,
      headline: t(`slides.${id}.headline` as Parameters<typeof t>[0]),
      body: t(`slides.${id}.body` as Parameters<typeof t>[0]),
    }
  })

  const handleDismiss = useCallback(() => {
    markTutorialComplete()
    onDismiss()
  }, [onDismiss])

  const handleNext = useCallback(() => {
    if (isLastSlide) {
      handleDismiss()
      return
    }
    setDirection(1)
    setCurrentSlide(prev => prev + 1)
  }, [isLastSlide, handleDismiss])

  const handleBack = useCallback(() => {
    if (currentSlide === 0) return
    setDirection(-1)
    setCurrentSlide(prev => prev - 1)
  }, [currentSlide])

  const handleSlideBodyClick = useCallback(() => {
    handleNext()
  }, [handleNext])

  const slide = slides[currentSlide]

  return (
    <motion.div
      className="fixed inset-0 z-[100]"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.25 }}
      role="dialog"
      aria-modal="true"
      aria-label="Fable introduction"
    >
      {/* Tutorial content */}
      <div className="h-full bg-background flex flex-col">

        {/* Skip button */}
        <div className="flex justify-end px-4 pt-4 pb-1 shrink-0">
          <button
            onClick={handleDismiss}
            className="flex items-center gap-1.5 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors px-3 py-1.5 rounded-full hover:bg-secondary"
            aria-label="Skip tutorial"
          >
            {t('skip')}
            <X className="w-3.5 h-3.5" />
          </button>
        </div>

        {/* Slide body — tap anywhere to advance */}
        <div
          className="flex-1 min-h-0 overflow-y-auto flex flex-col px-6 cursor-pointer select-none"
          onClick={handleSlideBodyClick}
        >
          {/* Inner wrapper: my-auto centers when content fits; scrollable when it doesn't */}
          <div className="my-auto flex flex-col gap-7 py-6">
            {/* Visual */}
            <div className="overflow-hidden">
              <AnimatePresence mode="wait" custom={direction}>
                <motion.div
                  key={`visual-${slide.id}`}
                  custom={direction}
                  variants={slideVariants}
                  initial="enter"
                  animate="center"
                  exit="exit"
                >
                  {slide.visual}
                </motion.div>
              </AnimatePresence>
            </div>

            {/* Text */}
            <AnimatePresence mode="wait" custom={direction}>
              <motion.div
                key={`text-${slide.id}`}
                custom={direction}
                variants={slideVariants}
                initial="enter"
                animate="center"
                exit="exit"
                className="text-center"
              >
                <h2 className="text-2xl font-semibold text-foreground mb-3 leading-tight text-balance">
                  {slide.headline}
                </h2>
                <p className="text-muted-foreground leading-relaxed text-pretty">
                  {slide.body}
                </p>
              </motion.div>
            </AnimatePresence>
          </div>
        </div>

        {/* Footer — dots + navigation */}
        <div
          className="shrink-0 px-6 pb-8 pt-5"
          onClick={e => e.stopPropagation()}
        >
          {/* Dot indicators */}
          <div className="flex justify-center gap-2 mb-6" role="tablist" aria-label="Slide indicators">
            {Array.from({ length: TUTORIAL_SLIDE_COUNT }).map((_, i) => (
              <button
                key={i}
                role="tab"
                aria-selected={i === currentSlide}
                aria-label={`Slide ${i + 1} of ${TUTORIAL_SLIDE_COUNT}`}
                onClick={() => {
                  setDirection(i > currentSlide ? 1 : -1)
                  setCurrentSlide(i)
                }}
                className={cn(
                  'rounded-full transition-all duration-300',
                  i === currentSlide
                    ? 'w-6 h-2 bg-primary'
                    : 'w-2 h-2 bg-muted-foreground/30 hover:bg-muted-foreground/60',
                )}
              />
            ))}
          </div>

          {/* Back / Next */}
          <div className="flex items-center justify-between">
            <button
              onClick={handleBack}
              className={cn(
                'flex items-center gap-1.5 text-sm font-medium px-4 py-2.5 rounded-full transition-colors',
                currentSlide === 0
                  ? 'invisible pointer-events-none'
                  : 'text-muted-foreground hover:text-foreground hover:bg-secondary',
              )}
              aria-label="Previous slide"
            >
              <ChevronLeft className="w-4 h-4" />
              {t('back')}
            </button>

            <button
              onClick={handleNext}
              className="flex items-center gap-1.5 text-sm font-semibold px-6 py-2.5 rounded-full bg-primary text-primary-foreground hover:bg-primary/90 transition-colors"
              aria-label={isLastSlide ? t('letsGo') : t('next')}
            >
              {isLastSlide ? t('letsGo') : t('next')}
              {!isLastSlide && <ChevronRight className="w-4 h-4" />}
            </button>
          </div>
        </div>

      </div>
    </motion.div>
  )
}
